#!/bin/bash
echo "Hello, World"
#!/bin/bash
find . -empty -printf "%f\n"
#!/bin/bash
find -type f -name "*.gif" | rev | cut -d "/" -f 1 | cut -d '.' -f 2- | rev | LC_ALL=C sort -f
#!/bin/bash
echo "$(cut -c 1 | tr -d '\n')"
#!/bin/bash
tail -n +2 | cut -f 1 | sort | uniq -c | sort -nr | head -11 | cut -c 9-
#!/bin/bash
find . -type f -name '*.js' -delete
#!/bin/bash
find -mindepth 1 -type d | wc -l
#!/bin/bash
ls -t . | head
#!/bin/bash
sort | uniq -u 
#!/bin/bash
egrep 'root' /etc/passwd
#!/bin/bash
egrep -c 'bin' /etc/passwd
#!/bin/bash
egrep -A 3 'root' /etc/passwd
#!/bin/bash
egrep -v 'bin' /etc/passwd
#!/bin/bash
egrep ^[[:alpha:]] /etc/ssh/sshd_config
#!/bin/bash
tr 'Ac' 'Ze'
#!/bin/bash
echo "\"(Ôo)'"
#!/bin/bash
tr -d Cc
#!/bin/bash
rev
#!/bin/bash
cut -f 1,6 -d ':' /etc/passwd | sort
#!/bin/bash
cat /etc/passwd
#!/bin/bash
cat /etc/passwd /etc/hosts
#!/bin/bash
tail -n 10 /etc/passwd
#!/bin/bash
head -n 10 /etc/passwd
#!/bin/bash
head -3 iacta | tail -1
#!/bin/bash
echo -e "Best School"  >> "\\*\\\\'\"Best School\"\\'\\\\*$\\?\\*\\*\\*\\*\\*:)"
#!/bin/bash
ls -la>ls_cwd_content
#!/bin/bash
tail -1 iacta >> iacta
